### ISSUE TITLE
File upload validation occurs before file is selected

### ISSUE THREAD

**Issue by jmccollum-woolpert** [googlemaps-samples/js-route-optimization-app#110]
When uploading a JSON or ZIP file, the validation error "File is required" appears the moment "Choose a file" is selected, before the user has selected any file. This error should only appear if the user cancels selecting a file and no file is already selected in the input field.

**Comment by MosabShaheen** [comment]
Hi @jmccollum-woolpert, I want to contribute and want to solve this bug. So, please provide me with the guideline

**Comment by jmccollum-woolpert** [comment]
Hi @MosabShaheen, thank you for your interest in contributing. This specific issue has been selected as part of an in-progress PR, but if you'd like to contribute elsewhere, please take a look at [Contributing.md](https://github.com/google/cfr/blob/main/CONTRIBUTING.md), follow the directions within, and then feel free to start looking at other issues.
